#!/usr/bin/env node
// Generates dist/assets.js: an ESM module mapping every public URL path
// under dist/client/_next/** to its content type and base64-encoded bytes.
//
// Why this exists: `vinext build` (via @cloudflare/vite-plugin) targets
// Cloudflare Workers' static-assets binding (`wrangler.jsonc`'s
// `assets.binding: "ASSETS"`, see dist/server/wrangler.json). The built
// worker (dist/server/index.js) calls `env.ASSETS.fetch(...)` for asset
// paths and falls through to app rendering when that binding is absent.
// funcbox has no equivalent binding, so nothing would ever serve
// dist/client's JS/CSS chunks. This script bakes those files into a plain
// ESM module funcbox-entry.js can import and serve directly — no
// filesystem access needed at request time (funcbox's bundle host is
// in-memory; see tmp/03-runtime.md).
//
// Run after `vinext build` (wired into `pnpm build`, see package.json).

import { createHash } from "node:crypto";
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const clientNextDir = path.join(root, "dist", "client", "_next");
const outFile = path.join(root, "dist", "assets.js");

const CONTENT_TYPES = {
  ".js": "text/javascript; charset=utf-8",
  ".mjs": "text/javascript; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".map": "application/json; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".webp": "image/webp",
  ".avif": "image/avif",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".txt": "text/plain; charset=utf-8",
};

function contentTypeFor(filePath) {
  return CONTENT_TYPES[path.extname(filePath)] ?? "application/octet-stream";
}

function walk(dir, base, out) {
  for (const entry of readdirSync(dir)) {
    const full = path.join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      walk(full, base, out);
    } else {
      out.push(full);
    }
  }
  return out;
}

function main() {
  const files = walk(clientNextDir, clientNextDir, []);
  if (files.length === 0) {
    throw new Error(`no files found under ${clientNextDir}; did "vinext build" run first?`);
  }

  /** @type {Record<string, { type: string; hash: string; data: string }>} */
  const assets = {};
  let totalBytes = 0;

  for (const filePath of files) {
    const relFromClient = "/" + path.relative(path.join(root, "dist", "client"), filePath).split(path.sep).join("/");
    const bytes = readFileSync(filePath);
    totalBytes += bytes.length;
    assets[relFromClient] = {
      type: contentTypeFor(filePath),
      // Weak validator, not used for cache invalidation logic (immutable,
      // hashed paths under /_next/static/ already invalidate by URL).
      // Kept for completeness / potential ETag use.
      hash: createHash("sha256").update(bytes).digest("hex").slice(0, 16),
      data: bytes.toString("base64"),
    };
  }

  const header = [
    "// AUTO-GENERATED by scripts/build-assets.mjs — do not edit by hand.",
    "// Regenerate with `pnpm build` (which runs this script after `vinext build`).",
    "",
    "/**",
    " * @typedef {{ type: string, hash: string, data: string }} AssetEntry",
    " * data is base64-encoded file content; decode with atob() + Uint8Array",
    " * at request time (see funcbox-entry.js).",
    " */",
    "",
    "/** @type {Record<string, AssetEntry>} */",
    "export const assets = " + JSON.stringify(assets, null, 0) + ";",
    "",
  ].join("\n");

  writeFileSync(outFile, header);

  const kib = (totalBytes / 1024).toFixed(1);
  const outKib = (Buffer.byteLength(header) / 1024).toFixed(1);
  console.log(
    `build-assets: embedded ${files.length} files (${kib} KiB raw, ${outKib} KiB as base64 in ${path.relative(root, outFile)})`,
  );
}

main();
